/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package windows.admin;

import java.awt.Color;

/**
 *
 * @author samuel_fd
 */
public class JPanel_Dashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JPanel_Dashboard.class.getName());
    
    int xMouse, yMouse;
    public JPanel_Dashboard() {
        initComponents();
        
        JPanel_Inicio main = new JPanel_Inicio();
        
        main.setSize(830,690);
        main.setLocation(0, 0);
        
        content.removeAll();
        content.add(main);
        content.revalidate();
        content.repaint();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        fondoPanel = new javax.swing.JPanel();
        tituloTxt = new javax.swing.JLabel();
        inicioBtn = new javax.swing.JPanel();
        inicioTxt = new javax.swing.JLabel();
        productosBtn = new javax.swing.JPanel();
        productosTxt = new javax.swing.JLabel();
        entradasBtn = new javax.swing.JPanel();
        entradasTxt = new javax.swing.JLabel();
        salidasBtn = new javax.swing.JPanel();
        salidasTxt = new javax.swing.JLabel();
        categoriasBtn = new javax.swing.JPanel();
        categoriasTxt = new javax.swing.JLabel();
        historialBtn = new javax.swing.JPanel();
        historialTxt = new javax.swing.JLabel();
        usersBtn = new javax.swing.JPanel();
        usersTxt = new javax.swing.JLabel();
        ajustesBtn = new javax.swing.JPanel();
        ajustesTxt = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        exitBtn = new javax.swing.JPanel();
        exitTxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1010, 720));
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondoPanel.setBackground(new java.awt.Color(55, 55, 55));
        fondoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloTxt.setBackground(new java.awt.Color(255, 255, 255));
        tituloTxt.setFont(new java.awt.Font("Adwaita Sans", 1, 16)); // NOI18N
        tituloTxt.setForeground(new java.awt.Color(255, 255, 255));
        tituloTxt.setText("Unicafe - ESTL");
        fondoPanel.add(tituloTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        inicioBtn.setBackground(new java.awt.Color(55, 55, 55));
        inicioBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        inicioBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inicioBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                inicioBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                inicioBtnMouseExited(evt);
            }
        });

        inicioTxt.setFont(new java.awt.Font("Adwaita Sans", 1, 13)); // NOI18N
        inicioTxt.setForeground(new java.awt.Color(255, 255, 255));
        inicioTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inicioTxt.setText("INICIO");

        javax.swing.GroupLayout inicioBtnLayout = new javax.swing.GroupLayout(inicioBtn);
        inicioBtn.setLayout(inicioBtnLayout);
        inicioBtnLayout.setHorizontalGroup(
            inicioBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inicioBtnLayout.createSequentialGroup()
                .addComponent(inicioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        inicioBtnLayout.setVerticalGroup(
            inicioBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inicioTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        fondoPanel.add(inicioBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 190, 50));

        productosBtn.setBackground(new java.awt.Color(55, 55, 55));
        productosBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        productosBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productosBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                productosBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                productosBtnMouseExited(evt);
            }
        });

        productosTxt.setFont(new java.awt.Font("Adwaita Sans", 1, 13)); // NOI18N
        productosTxt.setForeground(new java.awt.Color(255, 255, 255));
        productosTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        productosTxt.setText("PRODUCTOS");
        productosTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout productosBtnLayout = new javax.swing.GroupLayout(productosBtn);
        productosBtn.setLayout(productosBtnLayout);
        productosBtnLayout.setHorizontalGroup(
            productosBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(productosTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        productosBtnLayout.setVerticalGroup(
            productosBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(productosTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        fondoPanel.add(productosBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 190, 50));

        entradasBtn.setBackground(new java.awt.Color(55, 55, 55));
        entradasBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        entradasBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                entradasBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                entradasBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                entradasBtnMouseExited(evt);
            }
        });

        entradasTxt.setFont(new java.awt.Font("Adwaita Sans", 1, 13)); // NOI18N
        entradasTxt.setForeground(new java.awt.Color(255, 255, 255));
        entradasTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        entradasTxt.setText("ENTRADAS");

        javax.swing.GroupLayout entradasBtnLayout = new javax.swing.GroupLayout(entradasBtn);
        entradasBtn.setLayout(entradasBtnLayout);
        entradasBtnLayout.setHorizontalGroup(
            entradasBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(entradasTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        entradasBtnLayout.setVerticalGroup(
            entradasBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(entradasTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        fondoPanel.add(entradasBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 190, 50));

        salidasBtn.setBackground(new java.awt.Color(55, 55, 55));
        salidasBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salidasBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salidasBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salidasBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salidasBtnMouseExited(evt);
            }
        });

        salidasTxt.setFont(new java.awt.Font("Adwaita Sans", 1, 13)); // NOI18N
        salidasTxt.setForeground(new java.awt.Color(255, 255, 255));
        salidasTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salidasTxt.setText("SALIDAS");

        javax.swing.GroupLayout salidasBtnLayout = new javax.swing.GroupLayout(salidasBtn);
        salidasBtn.setLayout(salidasBtnLayout);
        salidasBtnLayout.setHorizontalGroup(
            salidasBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, salidasBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(salidasTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))
        );
        salidasBtnLayout.setVerticalGroup(
            salidasBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(salidasTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        fondoPanel.add(salidasBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 190, 50));

        categoriasBtn.setBackground(new java.awt.Color(55, 55, 55));
        categoriasBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        categoriasBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                categoriasBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                categoriasBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                categoriasBtnMouseExited(evt);
            }
        });

        categoriasTxt.setFont(new java.awt.Font("Adwaita Sans", 1, 13)); // NOI18N
        categoriasTxt.setForeground(new java.awt.Color(255, 255, 255));
        categoriasTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        categoriasTxt.setText("CATEGORIAS");

        javax.swing.GroupLayout categoriasBtnLayout = new javax.swing.GroupLayout(categoriasBtn);
        categoriasBtn.setLayout(categoriasBtnLayout);
        categoriasBtnLayout.setHorizontalGroup(
            categoriasBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(categoriasTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        categoriasBtnLayout.setVerticalGroup(
            categoriasBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(categoriasTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        fondoPanel.add(categoriasBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 180, 50));

        historialBtn.setBackground(new java.awt.Color(55, 55, 55));
        historialBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        historialBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                historialBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                historialBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                historialBtnMouseExited(evt);
            }
        });

        historialTxt.setFont(new java.awt.Font("Adwaita Sans", 1, 13)); // NOI18N
        historialTxt.setForeground(new java.awt.Color(255, 255, 255));
        historialTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        historialTxt.setText("HISTORIAL");

        javax.swing.GroupLayout historialBtnLayout = new javax.swing.GroupLayout(historialBtn);
        historialBtn.setLayout(historialBtnLayout);
        historialBtnLayout.setHorizontalGroup(
            historialBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(historialTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        historialBtnLayout.setVerticalGroup(
            historialBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(historialTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        fondoPanel.add(historialBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 180, 50));

        usersBtn.setBackground(new java.awt.Color(55, 55, 55));
        usersBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        usersBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usersBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                usersBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                usersBtnMouseExited(evt);
            }
        });

        usersTxt.setFont(new java.awt.Font("Adwaita Sans", 1, 13)); // NOI18N
        usersTxt.setForeground(new java.awt.Color(255, 255, 255));
        usersTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usersTxt.setText("USUARIOS");

        javax.swing.GroupLayout usersBtnLayout = new javax.swing.GroupLayout(usersBtn);
        usersBtn.setLayout(usersBtnLayout);
        usersBtnLayout.setHorizontalGroup(
            usersBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(usersTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        usersBtnLayout.setVerticalGroup(
            usersBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(usersTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        fondoPanel.add(usersBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 180, 50));

        ajustesBtn.setBackground(new java.awt.Color(55, 55, 55));
        ajustesBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ajustesBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ajustesBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ajustesBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ajustesBtnMouseExited(evt);
            }
        });

        ajustesTxt.setFont(new java.awt.Font("Adwaita Sans", 1, 13)); // NOI18N
        ajustesTxt.setForeground(new java.awt.Color(255, 255, 255));
        ajustesTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ajustesTxt.setText("CONFIGURACION");

        javax.swing.GroupLayout ajustesBtnLayout = new javax.swing.GroupLayout(ajustesBtn);
        ajustesBtn.setLayout(ajustesBtnLayout);
        ajustesBtnLayout.setHorizontalGroup(
            ajustesBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ajustesTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        ajustesBtnLayout.setVerticalGroup(
            ajustesBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ajustesTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        fondoPanel.add(ajustesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 670, 180, 50));

        bg.add(fondoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 190, 720));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );

        bg.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 830, 690));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        exitBtn.setBackground(new java.awt.Color(255, 255, 255));
        exitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitBtnMouseClicked(evt);
            }
        });

        exitTxt.setBackground(new java.awt.Color(255, 255, 255));
        exitTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTxt.setText("X");
        exitTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitBtnLayout = new javax.swing.GroupLayout(exitBtn);
        exitBtn.setLayout(exitBtnLayout);
        exitBtnLayout.setHorizontalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        exitBtnLayout.setVerticalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(0, 800, Short.MAX_VALUE)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bg.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inicioBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inicioBtnMouseEntered
        inicioBtn.setBackground(Color.gray);
    }//GEN-LAST:event_inicioBtnMouseEntered

    private void inicioBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inicioBtnMouseExited
       inicioBtn.setBackground(new Color(55,55,55));
    }//GEN-LAST:event_inicioBtnMouseExited

    private void inicioBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inicioBtnMouseClicked
         JPanel_Inicio main = new JPanel_Inicio();
        
        main.setSize(830,690);
        main.setLocation(0, 0);
        
        content.removeAll();
        content.add(main);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_inicioBtnMouseClicked

    private void productosBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productosBtnMouseEntered
        productosBtn.setBackground(Color.gray);
    }//GEN-LAST:event_productosBtnMouseEntered

    private void productosBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productosBtnMouseExited
        productosBtn.setBackground(new Color(55,55,55));
    }//GEN-LAST:event_productosBtnMouseExited

    private void productosBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productosBtnMouseClicked
        JPanel_Productos main = new JPanel_Productos();
        
        main.setSize(830,690);
        main.setLocation(0, 0);
        
        content.removeAll();
        content.add(main);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_productosBtnMouseClicked

    private void exitTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitTxtMouseClicked

    private void exitTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseEntered
        exitBtn.setBackground(Color.red);
        exitTxt.setForeground(Color.white);
    }//GEN-LAST:event_exitTxtMouseEntered

    private void exitTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseExited
        exitBtn.setBackground(Color.white);
        exitTxt.setForeground(Color.black);
    }//GEN-LAST:event_exitTxtMouseExited

    private void exitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_exitBtnMouseClicked

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse - header.getX(), y - yMouse - header.getY());
    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void entradasBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entradasBtnMouseEntered
          entradasBtn.setBackground(Color.gray);
    }//GEN-LAST:event_entradasBtnMouseEntered

    private void entradasBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entradasBtnMouseExited
          entradasBtn.setBackground(new Color(55,55,55));
    }//GEN-LAST:event_entradasBtnMouseExited

    private void entradasBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entradasBtnMouseClicked
        JPanel_Entradas main = new JPanel_Entradas();
        
        main.setSize(830,690);
        main.setLocation(0, 0);
        
        content.removeAll();
        content.add(main);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_entradasBtnMouseClicked

    private void salidasBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salidasBtnMouseEntered
        salidasBtn.setBackground(Color.gray);
    }//GEN-LAST:event_salidasBtnMouseEntered

    private void salidasBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salidasBtnMouseExited
        salidasBtn.setBackground(new Color(55,55,55));
    }//GEN-LAST:event_salidasBtnMouseExited

    private void salidasBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salidasBtnMouseClicked
        JPanel_Salidas main = new JPanel_Salidas();
        
        main.setSize(830,690);
        main.setLocation(0, 0);
        
        content.removeAll();
        content.add(main);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_salidasBtnMouseClicked

    private void categoriasBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoriasBtnMouseEntered
        categoriasBtn.setBackground(Color.gray);
    }//GEN-LAST:event_categoriasBtnMouseEntered

    private void categoriasBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoriasBtnMouseExited
        categoriasBtn.setBackground(new Color(55,55,55));
    }//GEN-LAST:event_categoriasBtnMouseExited

    private void categoriasBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoriasBtnMouseClicked
        JPanel_Categorias main = new JPanel_Categorias();
        
        main.setSize(830,690);
        main.setLocation(0, 0);
        
        content.removeAll();
        content.add(main);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_categoriasBtnMouseClicked

    private void historialBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historialBtnMouseEntered
        historialBtn.setBackground(Color.gray);
    }//GEN-LAST:event_historialBtnMouseEntered

    private void historialBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historialBtnMouseExited
        historialBtn.setBackground(new Color(55,55,55));
    }//GEN-LAST:event_historialBtnMouseExited

    private void historialBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historialBtnMouseClicked
        JPanel_Historial main = new JPanel_Historial();
        
        main.setSize(830,690);
        main.setLocation(0, 0);
        
        content.removeAll();
        content.add(main);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_historialBtnMouseClicked

    private void usersBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersBtnMouseEntered
        usersBtn.setBackground(Color.gray);
    }//GEN-LAST:event_usersBtnMouseEntered

    private void usersBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersBtnMouseExited
        usersBtn.setBackground(new Color(55,55,55));
    }//GEN-LAST:event_usersBtnMouseExited

    private void usersBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersBtnMouseClicked
        JPanel_Usuarios main = new JPanel_Usuarios();
        
        main.setSize(830,690);
        main.setLocation(0, 0);
        
        content.removeAll();
        content.add(main);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_usersBtnMouseClicked

    private void ajustesBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajustesBtnMouseEntered
        ajustesBtn.setBackground(Color.gray);
    }//GEN-LAST:event_ajustesBtnMouseEntered

    private void ajustesBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajustesBtnMouseExited
        ajustesBtn.setBackground(new Color(55,55,55));
    }//GEN-LAST:event_ajustesBtnMouseExited

    private void ajustesBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajustesBtnMouseClicked
        JPanel_Ajustes main = new JPanel_Ajustes();
        
        main.setSize(830,690);
        main.setLocation(0, 0);
        
        content.removeAll();
        content.add(main);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_ajustesBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JPanel_Dashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ajustesBtn;
    private javax.swing.JLabel ajustesTxt;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel categoriasBtn;
    private javax.swing.JLabel categoriasTxt;
    private javax.swing.JPanel content;
    private javax.swing.JPanel entradasBtn;
    private javax.swing.JLabel entradasTxt;
    private javax.swing.JPanel exitBtn;
    private javax.swing.JLabel exitTxt;
    private javax.swing.JPanel fondoPanel;
    private javax.swing.JPanel header;
    private javax.swing.JPanel historialBtn;
    private javax.swing.JLabel historialTxt;
    private javax.swing.JPanel inicioBtn;
    private javax.swing.JLabel inicioTxt;
    private javax.swing.JPanel productosBtn;
    private javax.swing.JLabel productosTxt;
    private javax.swing.JPanel salidasBtn;
    private javax.swing.JLabel salidasTxt;
    private javax.swing.JLabel tituloTxt;
    private javax.swing.JPanel usersBtn;
    private javax.swing.JLabel usersTxt;
    // End of variables declaration//GEN-END:variables
}
